-- MySQL Script generated by MySQL Workbench
-- Tue Aug 17 17:56:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejemplo1_BD2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ejemplo1_BD2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejemplo1_BD2` DEFAULT CHARACTER SET utf8 ;
USE `Ejemplo1_BD2` ;

-- -----------------------------------------------------
-- Table `Ejemplo1_BD2`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejemplo1_BD2`.`ciudades` (
  `nombre` VARCHAR(70) NOT NULL,
  `latitud` FLOAT NULL DEFAULT 0,
  `longitud` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejemplo1_BD2`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejemplo1_BD2`.`personas` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NULL,
  `ciudad_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_personas_ciudades_idx` (`ciudad_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_personas_ciudades`
    FOREIGN KEY (`ciudad_nombre`)
    REFERENCES `Ejemplo1_BD2`.`ciudades` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
